// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA60XTuFe5ZAE6Lgv-bt2EZUihBi4ecHKg',
    appId: '1:996953202936:web:ce515f94abd2e7b2e41b0d',
    messagingSenderId: '996953202936',
    projectId: 'fir-21a07',
    authDomain: 'fir-21a07.firebaseapp.com',
    storageBucket: 'fir-21a07.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDckqj8tLvWOVDk4aTEgM1jF4exfUbqcoU',
    appId: '1:996953202936:android:ea39134e2649bd69e41b0d',
    messagingSenderId: '996953202936',
    projectId: 'fir-21a07',
    storageBucket: 'fir-21a07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9OY5EnTaWulcjlmCNd7AjHRpCYD72YCI',
    appId: '1:996953202936:ios:f50a1b24d793981ee41b0d',
    messagingSenderId: '996953202936',
    projectId: 'fir-21a07',
    storageBucket: 'fir-21a07.appspot.com',
    iosClientId: '996953202936-n1vsu3lfmhop7pvfm14m1g8om9b94v1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9OY5EnTaWulcjlmCNd7AjHRpCYD72YCI',
    appId: '1:996953202936:ios:f50a1b24d793981ee41b0d',
    messagingSenderId: '996953202936',
    projectId: 'fir-21a07',
    storageBucket: 'fir-21a07.appspot.com',
    iosClientId: '996953202936-n1vsu3lfmhop7pvfm14m1g8om9b94v1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
